# Generated by Django 5.1.1 on 2024-09-23 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do animal')),
                ('especie', models.CharField(max_length=100, verbose_name='Especie')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('quantidade_total', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Quantidade total')),
                ('unid_medida', models.IntegerField(verbose_name='Unidade de medida')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do setor')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=100, verbose_name='Lote')),
                ('data_fabricacao', models.DateField(verbose_name='Data de fabricação')),
                ('data_validade', models.DateField(verbose_name='Data de validade')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Quantidade')),
                ('unid_medida', models.IntegerField(verbose_name='Unidade de medida')),
                ('quantidade_frascos', models.IntegerField(default=0, verbose_name='Quantidade de frascos')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='app.produto', verbose_name='Nome do produto')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
            },
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da saída')),
                ('horario', models.TimeField(verbose_name='Horário da saída')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Saída',
                'verbose_name_plural': 'Saídas',
            },
        ),
        migrations.CreateModel(
            name='Detalhes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('unid_medida', models.IntegerField(verbose_name='unidade de medida')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='app.produto', verbose_name='Produto retirado')),
                ('saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.saida', verbose_name='Saída referente')),
            ],
            options={
                'verbose_name': 'Detalhe',
                'verbose_name_plural': 'Detalhes',
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.setor', verbose_name='Setor pertencente'),
        ),
        migrations.AddField(
            model_name='animal',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.setor', verbose_name='Setor pertencente'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('CPF', models.CharField(max_length=100, verbose_name='CPF')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('funcao', models.IntegerField(verbose_name='Função')),
                ('perfil', models.IntegerField(verbose_name='Tipo de usuario')),
                ('senha', models.CharField(default='ifsuldeminas', max_length=100, verbose_name='Senha')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.setor', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.AddField(
            model_name='saida',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuario'),
        ),
    ]
