# Generated by Django 5.0.7 on 2024-07-29 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Função')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipos de produtos')),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data da saida')),
                ('horario', models.TimeField(verbose_name='horario da saida')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do setor')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='', verbose_name='imagem')),
                ('medida', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='medida')),
                ('unid_medida', models.CharField(max_length=2, verbose_name='unidade de medida')),
                ('lote', models.IntegerField(verbose_name='lote')),
                ('data_fabricacao', models.DateField(verbose_name='data de fabricação')),
                ('data_validade', models.DateField(verbose_name='data de validade')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produto', verbose_name='Nome do produto')),
            ],
        ),
        migrations.CreateModel(
            name='Detalhes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='quantidade')),
                ('unid_medida', models.CharField(max_length=2, verbose_name='unidade de medida')),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estoque', verbose_name='Produto retirado')),
                ('saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.saida', verbose_name='Saída referente')),
            ],
        ),
        migrations.AddField(
            model_name='saida',
            name='autorizado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.setor', verbose_name='Pessoa autorizada'),
        ),
        migrations.CreateModel(
            name='Autorizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('CPF', models.IntegerField(verbose_name='CPF')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.funcao', verbose_name='Funcao')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.setor', verbose_name='Funcao')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Animais trabalhados')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.setor', verbose_name='Setor pertencente')),
            ],
        ),
    ]
