# Generated by Django 5.1.1 on 2024-10-01 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(max_length=100, verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.setor', verbose_name='Setor Pertencente'),
        ),
        migrations.AlterField(
            model_name='detalhes',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='app.produto', verbose_name='Produto Retirado'),
        ),
        migrations.AlterField(
            model_name='detalhes',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='detalhes',
            name='saida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.saida', verbose_name='Saída Referente'),
        ),
        migrations.AlterField(
            model_name='detalhes',
            name='unid_medida',
            field=models.IntegerField(choices=[(1, 'Unidade'), (2, 'mL')], verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='data_fabricacao',
            field=models.DateField(verbose_name='Data de Fabricação'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='data_validade',
            field=models.DateField(verbose_name='Data de Validade'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='app.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='quantidade_frascos',
            field=models.IntegerField(default=0, verbose_name='Quantidade de Frascos'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='unid_medida',
            field=models.IntegerField(choices=[(1, 'Unidade'), (2, 'mL')], verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantidade Total'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.setor', verbose_name='Setor Pertencente'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unid_medida',
            field=models.IntegerField(choices=[(1, 'Unidade'), (2, 'mL')], verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='data',
            field=models.DateField(verbose_name='Data da Saída'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='horario',
            field=models.TimeField(verbose_name='Horário da Saída'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Setor'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='CPF',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='funcao',
            field=models.IntegerField(choices=[(1, 'Coordenador'), (2, 'Aluno Morador'), (3, 'Funcionário')], verbose_name='Função'),
        ),
    ]
