# Generated by Django 5.0.7 on 2024-08-05 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_autorizado_cpf_alter_autorizado_setor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animais'},
        ),
        migrations.AlterModelOptions(
            name='autorizado',
            options={'verbose_name': 'Autorizado', 'verbose_name_plural': 'Autorizados'},
        ),
        migrations.AlterModelOptions(
            name='detalhes',
            options={'verbose_name': 'Detalhe', 'verbose_name_plural': 'Detalhes'},
        ),
        migrations.AlterModelOptions(
            name='estoque',
            options={'verbose_name': 'Estoque', 'verbose_name_plural': 'Estoques'},
        ),
        migrations.AlterModelOptions(
            name='funcao',
            options={'verbose_name': 'Função', 'verbose_name_plural': 'Funções'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='saida',
            options={'verbose_name': 'Saída', 'verbose_name_plural': 'Saídas'},
        ),
        migrations.AlterModelOptions(
            name='setor',
            options={'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.RemoveField(
            model_name='detalhes',
            name='unid_medida',
        ),
        migrations.AddField(
            model_name='autorizado',
            name='senha',
            field=models.CharField(default='default_password', max_length=100, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do animal'),
        ),
        migrations.AlterField(
            model_name='autorizado',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='autorizado',
            name='funcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.funcao', verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='detalhes',
            name='quantidade',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='data_fabricacao',
            field=models.DateField(verbose_name='Data de fabricação'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='data_validade',
            field=models.DateField(verbose_name='Data de validade'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='imagem',
            field=models.ImageField(upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='lote',
            field=models.IntegerField(verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='medida',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Medida'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='unid_medida',
            field=models.CharField(max_length=2, verbose_name='Unidade de medida'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Tipo de produto'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='autorizado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.autorizado', verbose_name='Pessoa autorizada'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='data',
            field=models.DateField(verbose_name='Data da saída'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='horario',
            field=models.TimeField(verbose_name='Horário da saída'),
        ),
    ]
